### ISSUE TITLE
Uppercase words are not preserved

### ISSUE THREAD

**Issue by martinstuecklschwaiger** [EskaleraInc/catalyst-bias-correct#1]
“She's so aggressive” is changed to “she's so __assertive__”. 

It would be better if it stayed uppercase. 
Also I don't quite understand why you would highlight the changed words in the message? 

![Bias Correct](https://user-images.githubusercontent.com/1061218/54210471-d7c63e00-44df-11e9-84d0-924f95df4308.png)

**Comment by vivekatsuperset** [comment]
Sentence casing has been fixed.

As to the issue of highlighting the changed words, that was a design choice we made :-).
