### ISSUE TITLE
The handleChannelJoin message is sent to entire channel

### ISSUE THREAD

**Issue by sporkmonger** [EskaleraInc/catalyst-bias-correct#2]
It looks like it's sending to `https://slack.com/api/chat.postMessage` when `https://slack.com/api/chat.postEphemeral` was intended?

**Comment by rgmz** [comment]
I'm pretty sure this plugin requires individual users to explicitly authorize it, since it needs to post messages on their behalf.

**Comment by vivekatsuperset** [comment]
This issue has been fixed.  There are 2 cases that need to be handled: (1) App is added to an existing channel, in which case we need use postMessage to publish the welcome message to all users in the channel and (2) a new user is added to a channel that already has the App installed, in which case we use postEphemeral to display the welcome message to just the new user.
